apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  service-a
  labels:
    app: service-a
spec:
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - image: rinormaloku/service-loop
        name:  svc-a
        env:
        - name: SERVICE_NAME
          value: "Service A"
        - name: ECHO_SVC
          value: "http://service-b"
        ports:
        - containerPort:  3000
          name:  svc-a
---
kind: Service
apiVersion: v1
metadata:
  name: service-a
spec:
  selector:
    app: service-a
  ports:
  - name: http
    port: 80
    targetPort: 3000