apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  service-b
  labels:
    app: service-b
spec:
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - image: rinormaloku/service-loop:2
        name:  svc-b
        env:
        - name: SERVICE_NAME
          value: "Service B"
        - name: ECHO_SVC
          value: "http://service-a"
        ports:
        - containerPort:  3000
          name:  svc-b
---
kind: Service
apiVersion: v1
metadata:
  name: service-b
spec:
  selector:
    app: service-b
  ports:
  - name: http
    port: 80
    targetPort: 3000